// frontend/src/pages/auth/common/social.jsx
import React from "react";
// import images
import Google from "@/assets/images/icon/gp.svg";

const Social = () => {
  return (
      <div className="flex justify-center">
        <a
          href="#"
          className="inline-flex h-10 w-10 bg-[#000] text-white text-2xl flex-col items-center justify-center rounded-full"
        >
          <img src={Google} alt="" />
        </a>
      </div>
  );
};

export default Social;

// frontend/src/views/auth/common/Social.vue
<template>
  <ul class="flex justify-center">
    <li class="flex justify-center items-center">
      <a
        href="#"
        class="inline-flex h-10 w-10 bg-[#000] text-white text-2xl flex-col items-center justify-center rounded-full"
      >
        <img src="@/assets/images/icon/gp.svg" alt="" />
      </a>
    </li>
  </ul>
</template>
<script>
export default {};
</script>
<style lang=""></style>
