// frontend/src/components/partials/footer/index.jsx
import React from "react";
import useFooterType from "@/hooks/useFooterType";

const Footer = ({ className = "custom-class" }) => {
  const [footerType] = useFooterType();
  const footerclassName = () => {
    switch (footerType) {
      case "sticky":
        return "sticky bottom-0 z-[999]";
      case "static":
        return "static";
      case "hidden":
        return "hidden";
    }
  };
  return (
    <footer className={className + " " + footerclassName()}>
      <div className="site-footer px-6 bg-white dark:bg-slate-800 text-slate-500 dark:text-slate-300 py-4">
        <div className="grid md:grid-cols-2 grid-cols-1 md:gap-5">
          <div className="text-center ltr:md:text-start rtl:md:text-right text-sm">
            COPYRIGHT &copy; 2023 Entrepreneurship Cell, IIT Kharagpur, All rights Reserved
          </div>
          <div className="ltr:md:text-right rtl:md:text-end text-center text-sm">
            Visit GES 2024{" "}
            <a
              href="https://ges.ecell-iitkgp.org"
              target="_blank"
              className="text-primary-500 font-semibold"
            >
              Website
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// frontend/src/components/Footer/index.vue
<template>
  <footer :class="footerClass()">
    <div
      class="site-footer px-6 bg-white dark:bg-slate-800 text-slate-500 dark:text-slate-300 py-4"
    >
      <div class="grid md:grid-cols-2 grid-cols-1 md:gap-5">
        <div class="text-center ltr:md:text-start rtl:md:text-right text-sm">
          COPYRIGHT &copy; 2024 Entrepreneurship Cell, IIT Kharagpur, All rights Reserved
        </div>
        <div class="ltr:md:text-right rtl:md:text-end text-center text-sm">
          Visit GES'24
          <a
            href="https://ges.ecell-iitkgp.org"
            target="_blank"
            class="text-primary-500 font-semibold"
          >
            Website
          </a>
        </div>
      </div>
    </div>
  </footer>
</template>
<script>
export default {
  methods: {
    footerClass() {
      switch (this.$store.themeSettingsStore.footerType) {
        case "sticky":
          return "sticky bottom-0 z-[999]";
        case "static":
          return "static";
        case "hidden":
          return "hidden";
      }
    },
  },
};
</script>
<style lang=""></style>
