// frontend/src/views/professional/home/Analytics-Component/Teamtable.vue
<template>
  <div class="-mx-6 -mb-6">
    <vue-good-table
      :columns="columns"
      styleClass=" vgt-table lesspadding v-middle table-head borderless  rounded-md "
      :rows="teamtable"
      :pagination-options="{
        enabled: true,
        perPage: perpage,
      }"
      :sort-options="{
        enabled: false,
      }"
    >
      <template v-slot:table-row="props">
        
        <span
          v-if="props.column.field == 'customer'"
          class="flex items-center min-w-[150px]"
        >
          <span class="text-sm text-slate-600 dark:text-slate-300 capitalize">{{
            props.row.customer.name
          }}</span>
        </span>

        <span
          v-if="props.column.field == 'status'"
          class="block min-w-[140px] text-left"
        >
          <span class="inline-block text-center mx-auto py-1">
            <span
              v-if="props.row.status === 'progress'"
              class="flex items-center space-x-3 rtl:space-x-reverse"
            >
              <span
                class="h-[6px] w-[6px] bg-danger-500 rounded-full inline-block ring-4 ring-opacity-30 ring-danger-500"
              ></span>
              <span>In progress</span>
            </span>
            <span
              v-if="props.row.status === 'complete'"
              class="flex items-center space-x-3 rtl:space-x-reverse"
            >
              <span
                class="h-[6px] w-[6px] bg-success-500 rounded-full inline-block ring-4 ring-opacity-30 ring-success-500"
              ></span>

              <span>Complete</span>
            </span>
          </span>
        </span>
        
      </template>
      <template #pagination-bottom="props">
        <div class="py-4 px-3 justify-center hidden">
          <Pagination
            :total="50"
            :current="current"
            :per-page="perpage"
            :pageRange="pageRange"
            @page-changed="current = $event"
            :pageChanged="props.pageChanged"
            :perPageChanged="props.perPageChanged"
          >
            >
          </Pagination>
        </div>
      </template>
    </vue-good-table>
  </div>
</template>
<script>
import Dropdown from "@/components/Dropdown";
import Icon from "@/components/Icon";
import Pagination from "@/components/Pagination";
import { MenuItem } from "@headlessui/vue";
import { shapeLine4 } from "./data.js";

export default {
  components: {
    Pagination,
    Dropdown,
    Icon,
    MenuItem,
  },

  data() {
    return {
      shapeLine4,
      current: 1,
      perpage: 6,
      pageRange: 5,
      searchTerm: "",
      
      teamtable: [
        {
          customer: {
            name: "Registration",
            deg: "Ux designer",
          },
          status: "complete",
        },
        {
          customer: {
            name: "Payment",
            deg: "Ux designer",
          },
          status: "progress",
        },
        {
          customer: {
            name: "Travel",
            deg: "Ux designer",
          },
          status: "progress",
        },
        {
          customer: {
            name: "Kit",
            deg: "Ux designer",
          },
          status: "progress",
        },
        {
          customer: {
            name: "Accomodation",
            deg: "Ux designer",
          },
          status: "progress",
        },
        {
          customer: {
            name: "Certificate",
            deg: "Ux designer",
          },
          status: "progress",
        },
      ],
      columns: [
        {
          field: "customer",
        },
        {
          field: "status",
        },
      ],
    };
  },
};
</script>
<style lang="scss">
.vgt-table th {
    display: none; // This hides the header
  }
</style>

// frontend/src/components/partials/Table/team-table.jsx
import React, { useState, useMemo } from "react";
import { teamData } from "../../../constant/table-data";

import Icon from "@/components/ui/Icon";
import Dropdown from "@/components/ui/Dropdown";
import { Menu } from "@headlessui/react";
import Chart from "react-apexcharts";
import { colors } from "@/constant/data";

import {
  useTable,
  useRowSelect,
  useSortBy,
  useGlobalFilter,
  usePagination,
} from "react-table";

const COLUMNS = [
  {
    accessor: "step",
    Cell: (row) => {
      return (
        <span className="flex items-center">
          <span className="flex-none text-2xl text-slate-600 dark:text-slate-300">
            <Icon
              icon={row?.cell?.value.icon}
            />
          </span>
          <span className=" px-4 text-sm text-slate-800 dark:text-slate-100 capitalize">
            {row?.cell?.value.name}
          </span>
        </span>
      );
    },
  },

  {
    accessor: "status",
    Cell: (row) => {
      return (
        <span className="block  text-left">
          <span className="inline-block text-center mx-auto py-1">
            {row?.cell?.value === "progress" && (
              <span className="flex items-center space-x-3 rtl:space-x-reverse">
                <span className="h-[6px] w-[6px] bg-danger-500 rounded-full inline-block ring-4 ring-opacity-30 ring-danger-500"></span>
                <span>Incomplete</span>
              </span>
            )}
            {row?.cell?.value === "complete" && (
              <span className="flex items-center space-x-3 rtl:space-x-reverse">
                <span className="h-[6px] w-[6px] bg-success-500 rounded-full inline-block ring-4 ring-opacity-30 ring-success-500"></span>

                <span>Complete</span>
              </span>
            )}
          </span>
        </span>
      );
    },
  },
  
];

const TeamTable = () => {
  const columns = useMemo(() => COLUMNS, []);
  const data = useMemo(() => teamData, []);

  const tableInstance = useTable(
    {
      columns,
      data,
      initialState: {
        pageSize: 6,
      },
    },

    useGlobalFilter,
    useSortBy,
    usePagination,
    useRowSelect
  );
  const {
    getTableProps,
    getTableBodyProps,
    headerGroups,
    footerGroups,
    page,
    nextPage,
    previousPage,
    canNextPage,
    canPreviousPage,
    pageOptions,
    state,
    gotoPage,
    pageCount,
    setPageSize,
    setGlobalFilter,
    prepareRow,
  } = tableInstance;

  const { pageIndex, pageSize } = state;

  return (
    <>
      <div>
        <div className="overflow-x-auto -mx-6">
          <div className="inline-block min-w-full align-middle">
            <div className="overflow-hidden ">
              <table
                className="min-w-full divide-y divide-slate-100 table-fixed dark:divide-slate-700"
                {...getTableProps}
              >
                <tbody
                  className="bg-white divide-y divide-slate-100 dark:bg-slate-800 dark:divide-slate-700"
                  {...getTableBodyProps}
                >
                  {page.map((row) => {
                    prepareRow(row);
                    return (
                      <tr {...row.getRowProps()}>
                        {row.cells.map((cell) => {
                          return (
                            <td
                              {...cell.getCellProps()}
                              className="table-td py-2"
                            >
                              {cell.render("Cell")}
                            </td>
                          );
                        })}
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default TeamTable;
